### ISSUE TITLE
Release 3.0.1 when TypeScript 3.7.0 has been released

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/node-bunyan-adaptor#4]
As the export from https://github.com/microsoft/TypeScript/pull/32372 requires https://github.com/microsoft/TypeScript/pull/33050 for TypeScript not to complain about it

See also: [Announcing TypeScript 3.7 Beta](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/)

**Comment by mariusmarais** [comment]
Please include the definitions in the NPM package when this is done :)

**Comment by voxpelli** [comment]
@mariusmarais That's indeed what I intend, and just now I released `3.0.1` which does contain the type definitions :)

**Comment by voxpelli** [comment]
@mariusmarais You're using this module? If so: Lovely!

**Comment by mariusmarais** [comment]
Yes, it's working quite nicely to connect some bunyan-wanting libs to a different logger system, thanks!
